apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kanboard
  namespace: default
spec:
  valuesFrom:
    - kind: ConfigMap
      name: kanboard-config
      valuesKey: values.yaml
