apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/frigate
  - ../base/vless
  - ../base/kanboard
patchesStrategicMerge:
  - frigate-patch.yaml
  - vless-patch.yaml
  - kanboard-patch.yaml
